name: QRcodeLogin
on:
  workflow_dispatch:


jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: æ£€å‡ºä»“åº“
        uses: actions/checkout@v3
      - name: åˆ›å»ºnode
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: ğŸ”§ å®‰è£…GitHub CLIï¼Œå¹¶ä½¿ç”¨PATç™»å½•
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
          gh --version
          echo "${{ secrets.PAT }}" | gh auth login --with-token
          gh auth status
      - name: Cache node_modules in api directory
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ./api/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: å®‰è£…ä¾èµ–
        run: npm run install
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      - name: äºŒç»´ç ç™»å½•
        id: login
        run: npm run qrcode
        env:
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: push md
        if: always()
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          sed -i "s/<sub>çŠ¶æ€:.*<\\/sub>/<sub>çŠ¶æ€: å·²è¿‡æœŸ<\\/sub>/" README.md
          git add README.md
          git commit -m "æ›´æ–°çŠ¶æ€" || echo "æ— æ›´æ”¹"
          git push --quiet --force-with-lease